version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:15
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=pun
      - POSTGRES_DB=coedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 60s
      retries: 5
      timeout: 5s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "9090:80"
      - "9443:443"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pun@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgresql:
    driver: local
  pgadmin:
    driver: local
